#include "tx_sine_generator.h"
#include "stm32g4xx_hal.h"
#include <stdint.h>
#include <math.h>
#include "config.h"

// The sine wave buffer
uint16_t tx_sine_dac_buffer[TX_SIGNAL_WAVELENGTH_SAMPLES];

/**
 * @brief Initializes the tx_sine_dac_buffer array with a sine wave
 *
 * The array is filled with a sine wave of the specified amplitude and
 * wavelength. The sine wave is centered at DAC_MIDPOINT (2048, the
 * midpoint of the DAC output range) and has amplitude of DAC_AMPLITUDE
 * (2047, the maximum amplitude of the DAC output range). The sine wave
 * is sampled at a rate of TX_SIGNAL_SAMPL_RATE_HZ and has a wavelength
 * of TX_SIGNAL_WAVELENGTH_SAMPLES samples.
 */
void tx_sine_init_buffer(void)
{
	//first half circular buffer
    for (int i = 0; i < TX_SIGNAL_WAVELENGTH_SAMPLES; i++)
    {
        tx_sine_dac_buffer[i] = (uint16_t)(DAC_MIDPOINT + DAC_AMPLITUDE * sinf(2.0f * M_PI * i / TX_SIGNAL_WAVELENGTH_SAMPLES));
    	//tx_sine_dac_buffer[i] = 2048;
    }
}

/**
 * @brief Start generating a sine wave on the specified DAC channel
 *
 * The function is a wrapper around HAL_DAC_Start_DMA() that uses the
 * pre-computed sine wave stored in tx_sine_dac_buffer. The waveform is
 * generated by the DAC in DMA mode, and is driven by the specified
 * timer tim.
 *
 * @param dac The DAC peripheral to use
 * @param tim The timer peripheral to use as the trigger source
 */
void tx_sine_start(DAC_HandleTypeDef *dac, TIM_HandleTypeDef *tim)
{
	//enable DAC
	HAL_DAC_Start(dac, TX_DAC_CHANNEL);

	//We need to set the pin as output mode
	GPIO_InitTypeDef GPIO_InitStruct = {0};
	GPIO_InitStruct.Pin = GPIO_PIN_4;
	GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

	//Set the timer.
    HAL_TIM_Base_Start(tim);
    HAL_DAC_Start_DMA(dac, TX_DAC_CHANNEL, (uint32_t*)tx_sine_dac_buffer, TX_SIGNAL_WAVELENGTH_SAMPLES, DAC_ALIGN_12B_R);
}

